kind: pipeline
name: default

platform: linux/amd64

steps:
  build_and_test_go_checkmate:
    image: golang:1.23
    commands:
      - cd go-checkmate
      - go test ./...
      - go build -o checkmate-go .
    when:
      event: [push, tag, pull_request]
  renovate:
    image: renovate/renovate:latest@sha256:98cb3ed58e90f1813266243d65334d499a63b80fcdc8e4806c2a75c4fbc5616f
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://codeberg.org/api/v1
      RENOVATE_AUTODISCOVER: 'false'
      RENOVATE_REPOSITORIES: ${CI_REPO}
      RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
    when:
      - event: [manual, cron]
        cron: renovate_schedule