kind: pipeline
name: default

platform: linux/amd64

steps:
  build_and_test_betterscan:
    image: golang:1.23
    commands:
      - cd betterscan-core
      - go test ./...
      - go build -o betterscan .
    when:
      event: [push, tag, pull_request]
  renovate:
    image: renovate/renovate:latest@sha256:98cb3ed58e90f1813266243d65334d499a63b80fcdc8e4806c2a75c4fbc5616f
    environment:
      RENOVATE_PLATFORM: github
      RENOVATE_ENDPOINT: https://api.github.com
      RENOVATE_AUTODISCOVER: 'false'
      RENOVATE_REPOSITORIES: ${CI_REPO}
      RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
    when:
      - event: [manual, cron]
        cron: renovate_schedule

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  build_release_assets:
    image: golang:1.23
    commands:
      - chmod +x scripts/release-build.sh
      - ./scripts/release-build.sh
    when:
      event: tag

  publish_release:
    image: woodpeckerci/plugin-release
    settings:
      api_key:
        from_secret: RELEASE_TOKEN
      base_url: https://github.com
      files:
        - dist/betterscan_*.tar.gz
      checksum:
        - sha256
      checksum-file: checksums.txt
      checksum-flatten: true
    depends_on:
      - build_release_assets
    when:
      event: tag